### ISSUE TITLE
What is missing

### ISSUE THREAD

**Issue by nathan-ca** [okta/okta-sdk-python#133]
Here is my script, almost identical to the sample script in the README

```
from okta.client import Client as OktaClient
import asyncio
import os

config = {
    'orgUrl': os.getenv("OKTA_DOMAIN"),
    'token': os.getenv("OKTA_API_TOKEN")
}

client = OktaClient(config)

async def main():
    users, resp, err = await client.list_users()
    print(len(users))

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

Here is the error message
```
Traceback (most recent call last):
  File "okta-query.py", line 1, in <module>
    from okta.client import Client as OktaClient
  File "/Users/user/.python_3_envs/work_3.6/lib/python3.6/site-packages/okta/client.py", line 20, in <module>
    from okta.config.config_setter import ConfigSetter
  File "/Users/user/.python_3_envs/work_3.6/lib/python3.6/site-packages/okta/config/config_setter.py", line 4, in <module>
    from okta.constants import _GLOBAL_YAML_PATH, _LOCAL_YAML_PATH
  File "/Users/user/.python_3_envs/work_3.6/lib/python3.6/site-packages/okta/constants.py", line 2, in <module>
    import okta.models as models
  File "/Users/user/.python_3_envs/work_3.6/lib/python3.6/site-packages/okta/models/__init__.py", line 21, in <module>
    import okta.models.activate_factor_request as activate_factor_request
AttributeError: module 'okta' has no attribute 'models'

```

I'm using Python 3.6.8 and the okta library is 1.0.2 (most recent). Am I missing a library or setup step? Thanks.

**Comment by bretterer** [comment]
@nathan-ca Sorry for the troubles you are having here with the library.  It seems that there may be an issue with the install of the okta library you are experiencing.  We were having trouble in our initial release like this, and it was resolved in 1.0.2.

Could you please try running `pip uninstall okta` and trying to fully reinstall the package.  I have gotten report that just updating the package does not fully update for some reason.

Please run this step and see if that resolves your issue.

**Comment by nathan-ca** [comment]
Hi @bretterer,

I tried `pip uninstall okta` and `pip install okta`, issue remains. I also tried to clone the repo and rebuild the sdk, tox test printed many errors with the same ` AttributeError: module 'okta' has no attribute 'models' ` error message.

I'm switching back to REST API.

**Comment by serhiibuniak-okta** [comment]
@nathan-ca 
Could you please try it on a "clean" environment? i.e. virtualenv and install okta 1.0.2 or the latest (currently, 1.0.3) and run your script in the first post? Also, it would be good if you can provide some additional info:
1) Operating System
2) run python interpreter and execute command "from okta import models" - if it causes an error
3) check if folder `models` contains file `__init__.py`

**Comment by JonsSpaghetti** [comment]
@serhiibuniak-okta I'm not the original issue poster, but I can confirm that I'm also running into this issue both on my local machine that's a Mac running Catalina 10.15.7 as well as a docker container running Ubuntu 18.04.5 LTS.  

Local machine is on python 3.6.10, docker container is on 3.6.9

In both my local and docker installs of the okta sdk, the models folder does contain __init__.py, in fact when trying to import anything including okta.client, I get an error when attempting to process the okta.models imports contained in the okta/models/__init__.py

**Comment by serhiibuniak-okta** [comment]
@JonsSpaghetti Could you please, share the code (without any creds, of course) and traceback?
Does the following produce an error?
```
>>> import okta.models
>>> import okta.models.application # or any other module from models folder
```
Verify if `>>> okta.__version__` during the same session is not older than `1.0.2`

**Comment by JonsSpaghetti** [comment]
@serhiibuniak-okta I'm not even getting to the code because it's failing on import.

```
from okta.client import Client as OktaClient
import okta.models as models
```

Both of the above lines result in an error. 
The lines that you pasted produce the same error.

```
In [14]: okta.__version__
Out[14]: '1.0.3'
```

Traceback is as follows: 
```In [15]: import okta.models
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-82684dc69d41> in <module>()
----> 1 import okta.models

/usr/local/lib/python3.6/dist-packages/okta/models/__init__.py in <module>()
     19 # SEE CONTRIBUTOR DOCUMENTATION
     20
---> 21 import okta.models.activate_factor_request as activate_factor_request
     22 ActivateFactorRequest = activate_factor_request.ActivateFactorRequest
     23 import okta.models.app_and_instance_condition_evaluator_app_or_instance as app_and_instance_condition_evaluator_app_or_instance

AttributeError: module 'okta' has no attribute 'models'

In [16]: import okta.models.application
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-3004bba5c862> in <module>()
----> 1 import okta.models.application

/usr/local/lib/python3.6/dist-packages/okta/models/__init__.py in <module>()
     19 # SEE CONTRIBUTOR DOCUMENTATION
     20
---> 21 import okta.models.activate_factor_request as activate_factor_request
     22 ActivateFactorRequest = activate_factor_request.ActivateFactorRequest
     23 import okta.models.app_and_instance_condition_evaluator_app_or_instance as app_and_instance_condition_evaluator_app_or_instance

AttributeError: module 'okta' has no attribute 'models'
```

**Comment by JonsSpaghetti** [comment]
@sergiishamrai-okta After some other testing, it appears that this works fine in Python 3.7 & 3.8 so it's just a problem with 3.6.  Is 3.6 intended to be supported?

**Comment by serhiibuniak-okta** [comment]
@JonsSpaghetti Thank you for you efforts and detailed description. Yes, there is a problem, specific to python3.6 (it works in python3.5). Here's a description of a bug in Python itself: [https://bugs.python.org/issue30024](https://bugs.python.org/issue30024). It is fixed in 3.7
So, I suggest using Python3.7+. Hope, this helps.

**Comment by serhiibuniak-okta** [comment]
@nathan-ca try to update python, this (see post above) should solve your problem too.

**Comment by JonsSpaghetti** [comment]
@serhiibuniak-okta Got it, thanks for pointing me to the issue - that makes sense.

**Comment by JonsSpaghetti** [comment]
@serhiibuniak-okta Seems like this could be resolved by using the import syntax `from okta.models import x as y`.  How are the imports in the okta/models/__init__.py file generated?  I scanned the contributor documentation as well as the CLA FAQ and didn't see any info there.

If it's something that can be easily changed and would allow the sdk to support python 3.6 I'll happily make the change and PR it.

**Comment by serhiibuniak-okta** [comment]
@JonsSpaghetti The thing is this stuff is being generated based on openapi spec, thus it is not so easy to change imports, need to change spec.
@bretterer could you please, add few comments on it?

**Comment by bretterer** [comment]
@JonsSpaghetti thank you for all your input here.  As @sergiishamrai-okta stated, our SDK is generated based on our OpenAPI Spec file, which is an NPM package [@okta/openapi](https://www.npmjs.com/package/@okta/openapi).  That being said, if you wanted to change the import syntax in this SDK, you would want to update https://github.com/okta/okta-sdk-python/blob/master/openapi/templates/models-init.py.hbs which is the template that is used during the generation of `okta/models/__init__.py` file.  You should be able to run the generation process by running `yarn build` from the openapi folder after making changes

We always welcome PR contributions to our repos. I hope this bit of information helps you out a bit

**Comment by JonsSpaghetti** [comment]
@bretterer @serhiibuniak-okta  Perfect, thanks so much.  I'll go ahead and give that a try - if all goes well will put up a PR for that.

**Comment by serhiibuniak-okta** [comment]
@JonsSpaghetti fix is merged, thank you. We'll upload v1.0.4 to PYPI soon

**Comment by serhiibuniak-okta** [comment]
@JonsSpaghetti @nathan-ca v1.0.4 is ready

**Comment by bretterer** [comment]
@jonsSpaghetti, we have released the 1.0.4 version of the Python SDK which includes your changes. Thank you for your contribution to the SDK.

@nathan-ca, please update your SDK to our latest version that can be found on PyPi, and let us know if your issues have been resolved.

I am going to close this issue now as resolved, but please reach out to us if you find that this has not fixed your concerns here.

**Comment by nathan-ca** [comment]
@bretterer 

Just updated and confirm it's fixed. Thanks!

**Comment by bretterer** [comment]
Awesome!  Thank you for the confirmation @nathan-ca 

Please let us know if there is anything else we can help with
